name: readlexi_v1_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1+1
  path_provider: ^2.1.4
  path: ^1.9.0
  video_player: ^2.9.2
  image_gallery_saver_plus: ^4.0.1
  permission_handler: ^11.3.0
  device_info_plus: ^11.1.0
  http: ^1.2.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
